### ISSUE TITLE
segmentation violation error

### ISSUE THREAD

**Issue by dogadmin** [projectdiscovery/httpx#1348]
```bash
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x782d0c]

goroutine 10539199 [running]:
net/http.(*Client).do(0x1d8aa20?, 0x0)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/client.go:591 +0xcc
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/client.go:582
github.com/projectdiscovery/asnmap/libs.Client.makeRequest({0xc0001ca360, {{0x1d83bc0, 0xc000332000}, 0x0, {0x0, 0x0}, 0x0}})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/asnmap@v1.0.4/libs/client.go:153 +0x13c
github.com/projectdiscovery/asnmap/libs.Client.GetData({0xc0001ca360, {{0x1d83bc0, 0xc000332000}, 0x0, {0x0, 0x0}, 0x0}}, {0xc00a0c3f40, 0xe}, {0x0, ...})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/asnmap@v1.0.4/libs/client.go:187 +0x313
github.com/projectdiscovery/httpx/runner.(*Runner).analyze(_, _, {_, _}, {{0xc009921f40, 0x1a}, {0x0, 0x0}, {0x0, 0x0}}, ...)
        /home/runner/work/httpx/httpx/runner/runner.go:1602 +0x440f
github.com/projectdiscovery/httpx/runner.(*Runner).process.func1({{0xc009921f40, 0x1a}, {0x0, 0x0}, {0x0, 0x0}}, {0x1429175?, 0x0?}, {0x145dde8, 0xa})
        /home/runner/work/httpx/httpx/runner/runner.go:1107 +0x13b
created by github.com/projectdiscovery/httpx/runner.(*Runner).process
        /home/runner/work/httpx/httpx/runner/runner.go:1105 +0x898
```

**Comment by dogadmin** [comment]
Using the -l parameter, the issue arises when a single text file exceeds five million lines.
