### ISSUE TITLE
-asn Flag throws Error

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/httpx#1441]
### Current Behavior:

```
geekfreak@localhost ~ % httpx -u google.com -asn

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

		projectdiscovery.io

[INF] Current httpx version v1.3.6 (latest)
panic: runtime error: index out of range [15] with length 0

goroutine 25 [running]:
github.com/projectdiscovery/mapcidr.ipNetToRange({{0x0, 0x0, 0x0}, {0x14000c2dd00, 0x10, 0x10}})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.12/ip.go:289 +0x4c4
github.com/projectdiscovery/mapcidr.partitionCIDR({{0x14000c2dc60, 0x10, 0x10}, {0x14000c2dc70, 0x10, 0x10}}, {{0x0, 0x0, 0x0}, {0x14000c2dd00, ...}})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.12/ip.go:622 +0x190
github.com/projectdiscovery/mapcidr.rangeToCIDRs({0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.12/ip.go:599 +0x568
github.com/projectdiscovery/mapcidr.GetCIDRFromIPRange({0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.12/ip.go:1058 +0xe0
github.com/projectdiscovery/asnmap/libs.GetCIDR({0x1400032a8c0, 0x1, 0x1400069c260?})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/asnmap@v1.0.5/libs/cidr.go:12 +0x108
github.com/projectdiscovery/httpx/runner.(*Runner).analyze(_, _, {_, _}, {{_, _}, {_, _}, {_, _}}, ...)
	/home/runner/work/httpx/httpx/runner/runner.go:1666 +0x3424
github.com/projectdiscovery/httpx/runner.(*Runner).process.func1({{0x14000c2c060, 0xa}, {0x0, 0x0}, {0x0, 0x0}}, {0x1051e2b08?, 0x3?}, {0x10521768c, 0xa})
	/home/runner/work/httpx/httpx/runner/runner.go:1142 +0xe0
created by github.com/projectdiscovery/httpx/runner.(*Runner).process
	/home/runner/work/httpx/httpx/runner/runner.go:1140 +0x6fc
```

**Comment by dogancanbakir** [comment]
Tracked at https://github.com/projectdiscovery/asnmap/issues/212

**Comment by ehsandeep** [comment]
This issue now got fixed in dev branch:

```
go install -v github.com/projectdiscovery/httpx/cmd/httpx@dev
```
