### ISSUE TITLE
-asn throws panic error: index out of range

### ISSUE THREAD

**Issue by oscarintherocks** [projectdiscovery/httpx#1442]
### httpx version:
v1.3.6

### Current Behavior:
Using -asn option breaks httpx with a runtime error:
panic: runtime error: index out of range [15] with length 0

### Expected Behavior:
I expect httpx to handle the error

### Steps To Reproduce:
1. run: httpx -u google.com -asn
2. see error:
```
panic: runtime error: index out of range [15] with length 0

goroutine 26 [running]:
github.com/projectdiscovery/mapcidr.ipNetToRange({{0x0, 0x0, 0x0}, {0xc0006c6e10, 0x10, 0x10}})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.12/ip.go:289 +0x474
github.com/projectdiscovery/mapcidr.partitionCIDR({{0xc0006c6da0, 0x10, 0x10}, {0xc0006c6db0, 0x10, 0x10}}, {{0x0, 0x0, 0x0}, {0xc0006c6e10, ...}})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.12/ip.go:622 +0x199
github.com/projectdiscovery/mapcidr.rangeToCIDRs({0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.12/ip.go:599 +0x694
github.com/projectdiscovery/mapcidr.GetCIDRFromIPRange({0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.12/ip.go:1058 +0x146
github.com/projectdiscovery/asnmap/libs.GetCIDR({0xc000259760, 0x1, 0xc0007c2640?})
        /home/runner/go/pkg/mod/github.com/projectdiscovery/asnmap@v1.0.5/libs/cidr.go:12 +0x129
github.com/projectdiscovery/httpx/runner.(*Runner).analyze(_, _, {_, _}, {{0xc000d80060, 0xa}, {0x0, 0x0}, {0x0, 0x0}}, ...)
        /home/runner/work/httpx/httpx/runner/runner.go:1666 +0x44ff
github.com/projectdiscovery/httpx/runner.(*Runner).process.func1({{0xc000d80060, 0xa}, {0x0, 0x0}, {0x0, 0x0}}, {0x14f365b?, 0x3?}, {0x15283d3, 0xa})
        /home/runner/work/httpx/httpx/runner/runner.go:1142 +0x13b
created by github.com/projectdiscovery/httpx/runner.(*Runner).process
        /home/runner/work/httpx/httpx/runner/runner.go:1140 +0x898
```

Note that the mapcidr version included into httpx is not the last one available

**Comment by ehsandeep** [comment]
@oscarintherocks see https://github.com/projectdiscovery/httpx/issues/1441#issuecomment-1805364013

**Comment by oscarintherocks** [comment]
Thanks @ehsandeep I searched for that one but only for opened issues. Thanks again :)

**Comment by ehsandeep** [comment]
new release is now out with fix.
