### ISSUE TITLE
runtime: out of memory error: cannot allocate

### ISSUE THREAD

**Issue by MetzinAround** [projectdiscovery/httpx#1527]
From Discord 

OS : Windows 11, ROG Strix G713QM_G713QM
RAM : 32 Go
Httpx version : 1.3.7
I use a file of 60k lines
Here is the full error :
```
runtime: out of memory: cannot allocate 16777216-byte block (1693974528 in use)
fatal error: out of memory

goroutine 169922 [running]:
runtime.throw({0x15c0e26, 0xd})
        C:/Program Files (x86)/Go/src/runtime/panic.go:1047 +0x4d fp=0xe1ccf6c sp=0xe1ccf58 pc=0x5e999d
runtime.(*mcache).allocLarge(0x3821558, 0x1000000, 0x1)
        C:/Program Files (x86)/Go/src/runtime/mcache.go:236 +0x1be fp=0xe1ccf94 sp=0xe1ccf6c pc=0x5c45ce
runtime.mallocgc(0x1000000, 0x1410480, 0x1)
        C:/Program Files (x86)/Go/src/runtime/malloc.go:1053 +0x3eb fp=0xe1ccfcc sp=0xe1ccf94 pc=0x5bbeab
runtime.makeslice(0x1410480, 0x800000, 0x1000000)
        C:/Program Files (x86)/Go/src/runtime/slice.go:103 +0x4f fp=0xe1ccfe0 sp=0xe1ccfcc pc=0x5fe2ff
golang.org/x/net/html.(*Tokenizer).readByte(0xe2de1c0)
        C:/Users/Name/go/pkg/mod/golang.org/x/net@v0.17.0/html/token.go:249 +0x73 fp=0xe1cd01c sp=0xe1ccfe0 pc=0xc95943
golang.org/x/net/html.(*Tokenizer).readScript(0xe2de1c0)
        C:/Users/Name/go/pkg/mod/golang.org/x/net@v0.17.0/html/token.go:400 +0x6e fp=0xe1cd05c sp=0xe1cd01c pc=0xc9600e
golang.org/x/net/html.(*Tokenizer).readRawOrRCDATA(0xe2de1c0)
        C:/Users/Name/go/pkg/mod/golang.org/x/net@v0.17.0/html/token.go:330 +0x45 fp=0xe1cd06c sp=0xe1cd05c pc=0xc95d95
golang.org/x/net/html.(*Tokenizer).Next(0xe2de1c0)
        C:/Users/Name/go/pkg/mod/golang.org/x/net@v0.17.0/html/token.go:1011 +0x78 fp=0xe1cd080 sp=0xe1cd06c pc=0xc97608
golang.org/x/net/html.(*parser).parse(0xe2de310)
        C:/Users/Name/go/pkg/mod/golang.org/x/net@v0.17.0/html/parse.go:2319 +0xa7 fp=0xe1cd0d0 sp=0xe1cd080 pc=0xc93ea7
golang.org/x/net/html.ParseWithOptions({0x1db9c18, 0xdac62b8}, {0x0, 0x0, 0x0})
        C:/Users/Name/go/pkg/mod/golang.org/x/net@v0.17.0/html/parse.go:2385 +0x106 fp=0xe1cd0f4 sp=0xe1cd0d0 pc=0xc940b6
golang.org/x/net/html.Parse(...)
        C:/Users/Name/go/pkg/mod/golang.org/x/net@v0.17.0/html/parse.go:2344
github.com/projectdiscovery/httpx/common/httpx.getTitleWithDom(0xe6e4ea0)
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/common/httpx/title.go:55 +0xf6 fp=0xe1cd138 sp=0xe1cd0f4 pc=0x1242c76
github.com/projectdiscovery/httpx/common/httpx.ExtractTitle(0xe6e4ea0)
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/common/httpx/title.go:23 +0x28 fp=0xe1cd1b8 sp=0xe1cd138 pc=0x1242948
github.com/projectdiscovery/httpx/runner.(*Runner).analyze(0xc0a0410, 0xcacbbf0, {0xdb7b180, 0x5}, {{0xdb7b180, 0x73}, {0x0, 0x0}, {0x0, 0x0}}, ...)
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/runner/runner.go:1550 +0x380b fp=0xe1cdc20 sp=0xe1cd1b8 pc=0x132793b
github.com/projectdiscovery/httpx/runner.(*Runner).process.func1({{0xdb7b180, 0x73}, {0x0, 0x0}, {0x0, 0x0}}, {0x1569816, 0x3}, {0xdb7b180, 0x5})
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/runner/runner.go:1147 +0x118 fp=0xe1cdfbc sp=0xe1cdc20 pc=0x1323318
github.com/projectdiscovery/httpx/runner.(*Runner).process.func3()
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/runner/runner.go:1170 +0x5a fp=0xe1cdff0 sp=0xe1cdfbc pc=0x13231da
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1326 +0x1 fp=0xe1cdff4 sp=0xe1cdff0 pc=0x618831
created by github.com/projectdiscovery/httpx/runner.(*Runner).process
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/runner/runner.go:1145 +0x7a4

goroutine 1 [select]:
runtime.gopark(0x1aa2c34, 0x0, 0x9, 0x18, 0x1)
        C:/Program Files (x86)/Go/src/runtime/proc.go:381 +0xff fp=0xec73a68 sp=0xec73a54 pc=0x5ec99f
runtime.selectgo(0xec73b80, 0xec73b78, 0x0, 0x1, 0x1, 0x1)
        C:/Program Files (x86)/Go/src/runtime/select.go:327 +0xbc0 fp=0xec73b58 sp=0xec73a68 pc=0x5fbb90
github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).AddWithContext(0xeecf440, {0x1dbf47c, 0xc0220d8})
        C:/Users/Name/go/pkg/mod/github.com/remeh/sizedwaitgroup@v1.0.0/sizedwaitgroup.go:63 +0x95 fp=0xec73b94 sp=0xec73b58 pc=0x1299a95
github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).Add(...)
        C:/Users/Name/go/pkg/mod/github.com/remeh/sizedwaitgroup@v1.0.0/sizedwaitgroup.go:51
github.com/projectdiscovery/httpx/runner.(*Runner).process(0xc0a0410, {0xd60c360, 0x83}, 0xeecf440, 0xcacbbf0, {0xd60c360, 0x5}, 0xc0a041c, 0xdf101c0)
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/runner/runner.go:1144 +0x820 fp=0xec73cd8 sp=0xec73b94 pc=0x13229c0
github.com/projectdiscovery/httpx/runner.(*Runner).RunEnumeration.func3({0xd60c360, 0x83})
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/runner/runner.go:1038 +0x1aa fp=0xec73d28 sp=0xec73cd8 pc=0x131dd1a
github.com/projectdiscovery/httpx/runner.(*Runner).RunEnumeration.func4({0xc419200, 0x83, 0x900}, {0xca607a2, 0x0, 0x6})
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/runner/runner.go:1050 +0x4f fp=0xec73d44 sp=0xec73d28 pc=0x131db4f
github.com/projectdiscovery/hmap/store/disk.(*LevelDB).Scan(0xc0a8f20, {{0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, 0xe5fac78})
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/hmap@v0.0.24/store/disk/leveldb.go:224 +0x2b5 fp=0xec73df4 sp=0xec73d44 pc=0x1185cf5
github.com/projectdiscovery/hmap/store/hybrid.(*HybridMap).Scan(0xc0a8e20, 0xe5fac78)
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/hmap@v0.0.24/store/hybrid/hybrid.go:258 +0xbc fp=0xec73e5c sp=0xec73df4 pc=0x1188cec
github.com/projectdiscovery/httpx/runner.(*Runner).RunEnumeration(0xc0a0410)
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/runner/runner.go:1049 +0xb8a fp=0xec73f44 sp=0xec73e5c pc=0x131d6ca
main.main()
        C:/Users/Name/go/pkg/mod/github.com/projectdiscovery/httpx@v1.3.7/cmd/httpx/httpx.go:59 +0x3c7 fp=0xec73fc4 sp=0xec73f44 pc=0x1342987
runtime.main()
        C:/Program Files (x86)/Go/src/runtime/proc.go:250 +0x22e fp=0xec73ff0 sp=0xec73fc4 pc=0x5ec56e
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1326 +0x1 fp=0xec73ff4 sp=0xec73ff0 pc=0x618831

goroutine 2 [force gc (idle), 25 minutes]:
runtime.gopark(0x1aa2c04, 0x2740c58, 0x11, 0x14, 0x1)
        C:/Program Files (x86)/Go/src/runtime/proc.go:381 +0xff fp=0xc059fdc sp=0xc059fc8 pc=0x5ec99f
runtime.goparkunlock(...)
        C:/Program Files (x86)/Go/src/runtime/proc.go:387
runtime.forcegchelper()
        C:/Program Files (x86)/Go/src/runtime/proc.go:305 +0xcf fp=0xc059ff0 sp=0xc059fdc pc=0x5ec7cf
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1326 +0x1 fp=0xc059ff4 sp=0xc059ff0 pc=0x618831
created by runtime.init.5
        C:/Program Files (x86)/Go/src/runtime/proc.go:293 +0x23

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1aa2c04, 0x2741630, 0xc, 0x14, 0x1)
        C:/Program Files (x86)/Go/src/runtime/proc.go:381 +0xff fp=0xc05afcc sp=0xc05afb8 pc=0x5ec99f
runtime.goparkunlock(...)
        C:/Program Files (x86)/Go/src/runtime/proc.go:387
runtime.bgsweep(0xc0281c0)
        C:/Program Files (x86)/Go/src/runtime/mgcsweep.go:319 +0xf2 fp=0xc05afe8 sp=0xc05afcc pc=0x5d4992
runtime.gcenable.func1()
        C:/Program Files (x86)/Go/src/runtime/mgc.go:178 +0x27 fp=0xc05aff0 sp=0xc05afe8 pc=0x5c6be7
runtime.goexit()
        C:/Program Files (x86)/Go/src/runtime/asm_386.s:1326 +0x1 fp=0xc05aff4 sp=0xc05aff0 pc=0x618831
created by runtime.gcenable
        C:/Program Files (x86)/Go/src/runtime/mgc.go:178 +0x7c

goroutine 4 [sleep]:
runtime.gopark(0x1aa2c04, 0x2741cc0, 0x13, 0x13, 0x2)
        C:/Program Files (x86)/Go/src/runtime/proc.go:381 +0xff fp=0xc05bf64 sp=0xc05bf50 pc=0x5ec99f
runtime.goparkunlock(...)
        C:/Program Files (x86)/Go/src/runtime/proc.go:387
... (352 KB left)
```

**Comment by jimen0** [comment]
Given how the command line tool works you would be better doing a de-duplication phase first and then processing the file as a stream.

```
   -s, -stream                   stream mode - start elaborating input targets without sorting
   -sd, -skip-dedupe             disable dedupe input items (only used with stream mode)
```

These flags should be helpful.

**Comment by acidvegas** [comment]
It's not only that. `-stream` and `-sd` will help but HTTPX has stupid memory leak issues. My problems with this stopped after swithcing to a box with atleast 4gb of RAM. Alll my HTTPX scans would stop for no reason prior.

Make sure you don't have an OOM running (out of memory daemon)

**Comment by jimen0** [comment]
If you share a memory profile showing the leak I'll be happy to contribute a fix sometime around next month.
