### ISSUE TITLE
ValueError: unknown url type when using `transport=MockTransport(),base_url=""` 

### ISSUE THREAD

**Issue by tcrasset** [projectdiscovery/httpx#1563]
### httpx version:

`0.23.3`

### Current Behavior:

Passing no url to `httpx.Client` with a `MockTransport` is allowed, but a weird error pops up when actually calling an endpoint.

### Expected Behavior:
I expected to not be allowed to do that, or get a good error message.

### Steps To Reproduce:

```python
import httpx
httpx.Client(base_url="", transport=httpx.MockTransport(lambda x: httpx.Response(200))).request("GET", "datasets/")
```

See error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tom/.cache/pypoetry/virtualenvs/avatars-8_XMOapb-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/tom/.cache/pypoetry/virtualenvs/avatars-8_XMOapb-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 908, in send
    response = self._send_handling_auth(
  File "/home/tom/.cache/pypoetry/virtualenvs/avatars-8_XMOapb-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/tom/.cache/pypoetry/virtualenvs/avatars-8_XMOapb-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/tom/.cache/pypoetry/virtualenvs/avatars-8_XMOapb-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1017, in _send_single_request
    self.cookies.extract_cookies(response)
  File "/home/tom/.cache/pypoetry/virtualenvs/avatars-8_XMOapb-py3.10/lib/python3.10/site-packages/httpx/_models.py", line 1037, in extract_cookies
    urllib_request = self._CookieCompatRequest(response.request)
  File "/home/tom/.cache/pypoetry/virtualenvs/avatars-8_XMOapb-py3.10/lib/python3.10/site-packages/httpx/_models.py", line 1183, in __init__
    super().__init__(
  File "/usr/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/usr/lib/python3.10/urllib/request.py", line 352, in full_url
    self._parse()
  File "/usr/lib/python3.10/urllib/request.py", line 381, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/datasets/'
```

**Comment by tcrasset** [comment]
Errm, wrong `httpx` project, closing this.
