### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Ayush765** [projectdiscovery/httpx#656]
Traceback (most recent call last):
  File "/usr/local/bin/httpx", line 33, in <module>
    sys.exit(load_entry_point('httpx==1.0.0b0', 'console_scripts', 'httpx')())
  File "/usr/local/bin/httpx", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for httpx

**Comment by AaronChen0** [comment]
#516
#632

**Comment by Ayush765** [comment]
Thanks :)
