### ISSUE TITLE
使用python3 运行报错了，提示没有文件，但是有tmp 这个文件呀 ，求解决

### ISSUE THREAD

**Issue by 1554073781** [projectdiscovery/httpx#965]
Traceback (most recent call last):
  File "/opt/url_batch_discovery/url_batch_discovery.py", line 209, in <module>
    main(file, match_string, output_path, ports, threads)
  File "/opt/url_batch_discovery/url_batch_discovery.py", line 118, in main
    info['status-code'] = i['status-code']
KeyError: 'status-code'
Exception in thread Thread-1 (shengyu):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/url_batch_discovery/url_batch_discovery.py", line 19, in shengyu
    with open(subdoamin_url_file) as subdomain_f:
FileNotFoundError: [Errno 2] No such file or directory: './tmp/clear_url.txt'

**Comment by ehsandeep** [comment]
See https://github.com/projectdiscovery/httpx/discussions/516#discussioncomment-2140533
