### ISSUE TITLE
crash - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by deadjdona** [projectdiscovery/httpx#977]
### httpx version:
httpx@v1.2.7

### Current Behavior:
```console
httpx -u https._tcp.cloud.asdf.com -pa

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.7

		projectdiscovery.io

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1009a2f48]

goroutine 86 [running]:
github.com/projectdiscovery/httpx/runner.(*Runner).targets.func1()
	/home/runner/work/httpx/httpx/runner/runner.go:1008 +0x208
created by github.com/projectdiscovery/httpx/runner.(*Runner).targets
	/home/runner/work/httpx/httpx/runner/runner.go:973 +0x104
```

**Comment by ehsandeep** [comment]
@deadjdona can you provider curl or any other example showing `_tcp.cloud.asdf.com` can be accessed?

**Comment by deadjdona** [comment]
There's no problem with _tcp.cloud.asdf.com, problem is here:
> /home/user/go/bin/httpx -u https._tcp.cloud.asdf.com -location -server -td -ip -cname -cdn -pa -csp-probe -o gr-httpx.txt -r r.conf -fr -stats -ec -v -debug
